#!/bin/sh
echo "Running spotlessApply before commit..."
./gradlew spotlessApply

# 변경된 파일 다시 스테이징
git add .

# 실패 시 커밋 중단
if [ $? -ne 0 ]; then
  echo "spotlessApply failed, commit aborted!"
  exit 1
fi