version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - ./gradlew dependencies
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 329409317911.dkr.ecr.ap-northeast-2.amazonaws.com
      - echo Successfully logged in to Amazon ECR
  build:
    commands:
      - echo Building the project without tests...
      - ./gradlew build -x test
      - echo Building the Docker image...
      - docker build -t daily-todo-calendar-backend .
      - docker tag daily-todo-calendar-backend:latest 329409317911.dkr.ecr.ap-northeast-2.amazonaws.com/daily-todo-calendar-backend:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 329409317911.dkr.ecr.ap-northeast-2.amazonaws.com/daily-todo-calendar-backend:latest
      - echo Docker image successfully pushed to ECR

artifacts:
  files:
    - build/libs/*.jar
  discard-paths: yes

environment:
  computeType: BUILD_GENERAL1_SMALL
  image: aws/codebuild/amazonlinux2-x86_64-standard:4.0