version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - ./gradlew assemble
      - nohup /usr/local/bin/dockerd-entrypoint.sh &>/tmp/docker.log &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 329409317911.dkr.ecr.ap-northeast-2.amazonaws.com
      - echo Successfully logged in to Amazon ECR
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t daily-todo-calendar-backend -f Dockerfile.prd .
      - echo Tagging the Docker image...
      - docker tag daily-todo-calendar-backend:latest 329409317911.dkr.ecr.ap-northeast-2.amazonaws.com/daily-todo-calendar-backend:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 329409317911.dkr.ecr.ap-northeast-2.amazonaws.com/daily-todo-calendar-backend:latest
      - echo Writing imagedefinitions.json for ECS deployment...
      - printf '[{"name":"daily-todo-calendar-backend","imageUri":"%s"}]' 329409317911.dkr.ecr.ap-northeast-2.amazonaws.com/daily-todo-calendar-backend:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

cache:
  paths:
    - ~/.gradle/caches/
    - build/
