version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/memo?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
    container_name: spring-boot-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      retries: 5
      timeout: 5s

  frontend:
    build:
      context: ../daily-todo-calendar-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ../daily-todo-calendar-frontend:/usr/src/app  # 개발 환경에서만 사용
    environment:
      REACT_APP_API_URL: http://spring-boot-app:8080  # Docker Compose 네트워크 내부에서 동작
    container_name: frontend-container
    depends_on:
      app:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: memo
    ports:
      - "3306:3306"
    container_name: mysql-container
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  db_data:
