spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/memo?serverTimezone=UTC
    username: root
    password: Pass!1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: INFO
    sql: debug
    org.hibernate.orm.jdbc.bind: trace

file:
  name: ""

secret-key: "Iz*%8`Meukzodgl:v';Bj[(<;/k%J~Z-(Z;'q;Eig>hZDl2J@/w&gX@[U,[?W%Fg"