spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/memo}
    username: ${SPRING_DATASOURCE_USERNAME:postgre}
    password: ${SPRING_DATASOURCE_PASSWORD:password123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.dailytodocalendar: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

secret-key: ${JWT_SECRET_KEY:9tQphvO+2giE3K16TJq690LCxGKazukQvf6MGwmGyfrmuAwMJZ4g+dJJGFNEXWFKSnUKk5hklhh9BCGEBZi/Zw==}
