spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:20}
      minimum-idle: ${DB_MIN_IDLE:10}
      connection-timeout: 20000
      idle-timeout: 600000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
    min-response-size: 1024
  error:
    include-message: never
    include-binding-errors: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /management
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    root: INFO
    com.dailytodocalendar: INFO
    org.springframework: INFO
    org.hibernate: INFO
  file:
    name: /var/log/dailytodocalendar/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7

secret-key: ${JWT_SECRET_KEY}
