spring:
  application:
    name: daily-todo-calendar
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
  security:
    user:
      name: actuator
      password: ${ACTUATOR_PASSWORD:actuator123}
      roles: ACTUATOR_ADMIN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  info:
    env:
      enabled: true
    git:
      enabled: true
    build:
      enabled: true
    java:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.dailytodocalendar.api

jwt:
  expiration: 7200000  # 2시간
  refresh-expiration: 604800000  # 7일

oauth2:
  kakao:
    client-id: ${sm://kakao-client-id}
    client-secret: ${sm://kakao-client-secret}
    redirect-uri: ${sm://kakao-redirect-uri:http://localhost:3000/auth/kakao/callback}

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/memo}
    username: ${SPRING_DATASOURCE_USERNAME:postgre}
    password: ${SPRING_DATASOURCE_PASSWORD:password123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: simple

logging:
  level:
    root: INFO
    com.dailytodocalendar: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

secret-key: ${JWT_SECRET_KEY:a8c06ffd71cb6fdfa7929ee25247922e1b642a1c104d16944596613e96ae553c}

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:20}
      minimum-idle: ${DB_MIN_IDLE:10}
      connection-timeout: 20000
      idle-timeout: 600000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  cache:
    type: ${CACHE_TYPE:caffeine}
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1h

server:
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
    min-response-size: 1024
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /management
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    root: INFO
    com.dailytodocalendar: INFO
    org.springframework: INFO
    org.hibernate: INFO
  file:
    name: /var/log/dailytodocalendar/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7

secret-key: ${JWT_SECRET_KEY}