spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/memo?serverTimezone=UTC
    username: root
    password: Pass!1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    session:
      cookie:
        path: /
        name: JSESSIONID
        http-only: true
        # domain:
        # secure: true
      timeout: 3600

logging:
  level:
    root: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    com.dailytodocalendar: DEBUG
  file:
    name: ""

secret-key: "Iz*%8`Meukzodgl:v';Bj[(<;/k%J~Z-(Z;'q;Eig>hZDl2J@/w&gX@[U,[?W%Fg"