spring:
  application:
    name: daily-todo-calendar
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
  security:
    user:
      name: actuator
      password: ${ACTUATOR_PASSWORD:actuator123}
      roles: ACTUATOR_ADMIN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  info:
    env:
      enabled: true
    git:
      enabled: true
    build:
      enabled: true
    java:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.dailytodocalendar.api

jwt:
  expiration: 7200000  # 2시간
  refresh-expiration: 604800000  # 7일

oauth2:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:3000/auth/kakao/callback}
    admin-key: ${KAKAO_ADMIN_KEY}

server:
  error:
    include-stacktrace: never
