spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  servlet:
    session:
      cookie:
        path: /
        name: JSESSIONID
        http-only: true
        # domain:
        # secure: true
      timeout: 3600

secret-key: "Iz*%8`Meukzodgl:v';Bj[(<;/k%J~Z-(Z;'q;Eig>hZDl2J@/w&gX@[U,[?W%Fg"